### ISSUE TITLE
Popularity scores

### ISSUE THREAD

**Issue by bgantick** [apostrophecms/apostrophe-docs-popularity#1]
Assuming a `score` of `1` is weighted heavier than a `score` of `3`. This should be documented.

**Comment by boutell** [comment]
Yep. I'll clarify the math.

**Comment by boutell** [comment]
(It's the reverse. Mo' points = mo' better.)

**Comment by boutell** [comment]
(Otherwise things with no social scores at all would be most popular, which wouldn't make sense.)
