### ISSUE TITLE
RP retries vs. timeout

### ISSUE THREAD

**Issue by bgantick** [apostrophecms/apostrophe-docs-popularity#2]
Would it make more sense to use `request-promise`'s timeout option here instead of stacking retries (and taking the api limit hit)?
https://github.com/apostrophecms/apostrophe-docs-popularity/blob/master/index.js#L5

**Comment by boutell** [comment]
timeout and retry are different things. We're using the default timeout which is quite long, this code is intended to cope when the response is more like "500 error, we stubbed our toe, hopping on one foot and waiting for you to try again." Shouldn't hit the api limit if the response was an error. (API limit is very high for this service.)
